apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    owner: "durga"
    project: "task-manager-app"
spec:
  ingressClassName: task-manager-ingress
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service    
                port:
                  number: 80         